Add function to add client configuration

diff --git a/wg-cli b/wg-cli
--- a/wg-cli
+++ b/wg-cli
@@ -100,10 +100,10 @@ create_client()
     fi
 
     # Get the private key of the client
-    CLIENT_PRIVATE_KEY="`cat $TARGET_FOLDER/$CLIENT_PATH/keys/publickey 2>/dev/null`"
+    CLIENT_PRIVATE_KEY="`cat $TARGET_FOLDER/$CLIENT_PATH/keys/privatekey 2>/dev/null`"
     if [ -z "$CLIENT_PRIVATE_KEY" ]; then
         generate_key $CLIENT_PATH
-        CLIENT_PRIVATE_KEY="`cat $TARGET_FOLDER/$CLIENT_PATH/keys/publickey 2>/dev/null`"
+        CLIENT_PRIVATE_KEY="`cat $TARGET_FOLDER/$CLIENT_PATH/keys/privatekey 2>/dev/null`"
     fi
 
     echo ""
@@ -129,10 +129,35 @@ AllowedIPs = 0.0.0.0/0, ::/0
 
 add_client()
 {
+    CLIENT_PATH=$1
+    CLIENT_IP=$2
+    CLIENT_TARGET_PATH="$TARGET_FOLDER/$CLIENT_PATH"
+    SERVER_CONFIGURATION_FILE_PATH="$TARGET_FOLDER/wg0.conf"
+
+    # Get the public key of the client
+    CLIENT_PUBLIC_KEY="`cat $TARGET_FOLDER/$CLIENT_PATH/keys/publickey 2>/dev/null`"
+    if [ -z "$CLIENT_PUBLIC_KEY" ]; then
+        generate_key $CLIENT_PATH
+        CLIENT_PUBLIC_KEY="`cat $TARGET_FOLDER/$CLIENT_PATH/keys/publickey 2>/dev/null`"
+    fi
+
+    if [ ! -f "$SERVER_CONFIGURATION_FILE_PATH" ]; then
+        echo "Server configuration is missing… Generating a new one and continue !"
+        init_server
+    fi
+
     echo ""
-    echo "================================================="
-    echo "= Add client « $1 » to the server configuration ="
-    echo "================================================="
+    echo "================================================"
+    echo "= Add the client into the server configuration ="
+    echo "================================================"
+
+echo "
+[Peer]
+PublicKey = $CLIENT_PUBLIC_KEY
+AllowedIPs = $CLIENT_IP" >> $SERVER_CONFIGURATION_FILE_PATH
+
+    echo ""
+    echo "Configuration updated. Reload the server to update the loaded configuration."
 
 }
 
@@ -163,19 +188,33 @@ while [ "$1" != "" ]; do
                                 ;;
         -c | --create-client )  shift
                                 if [ -z "$1" ]; then
-                                    echo "Usage: wg-cli -c client_name"
+                                    echo "Usage: wg-cli -c client_name IP/MASK (ex. wg-cli -c pixel4 '10.200.200.2/32')"
+                                    exit 1
+                                elif [ -z "$2" ]; then
+                                    echo "Usage: wg-cli -c client_name IP/MASK (ex. wg-cli -c pixel4 '10.200.200.2/32')"
                                     exit 1
                                 else
-                                    # TODO => IP PARAM
-                                    create_client "clients/$1" "10.200.200.2/32"
+                                    create_client "clients/$1" "$2"
                                 fi
                                 exit
                                 ;;
         -a | --add-client )     shift
-                                add_client
+                                if [ -z "$1" ]; then
+                                    echo "Usage: wg-cli -a client_name IP/MASK (ex. wg-cli -a pixel4 '10.200.200.2/32')"
+                                    exit 1
+                                elif [ -z "$2" ]; then
+                                    echo "Usage: wg-cli -a client_name IP/MASK (ex. wg-cli -a pixel4 '10.200.200.2/32')"
+                                    exit 1
+                                else
+                                    add_client "clients/$1" "$2"
+                                fi
                                 exit
                                 ;;
         -q | --get-client-qr )  shift
+                                if [ -z "$1" ]; then
+                                    echo "Usage: wg-cli -q client_name"
+                                    exit 1
+                                fi
                                 get_client_qr "clients/$1"
                                 exit
                                 ;;
